### ISSUE TITLE
airspeed_mps is an array, 

### ISSUE THREAD

**Issue by nagordon** [sobester/ADRpy#3]
currently get the error

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

in line 660 of atmospheres.py, the airspeed_mps, I think, is an array. for the boolean operation, if you add .any() it works

    def mach(self, airspeed_mps, altitude_m=0):
        """Mach number at a given speed (m/s) and altitude (m)"""

        # Airspeed may be negative, e.g., when simulating a tailwind, but Mach must be >0
        if airspeed_mps.any() < 0:
            negmsg = "Airspeed < 0. If intentional, ignore this. Positive Mach no. returned."
            warnings.warn(negmsg, RuntimeWarning)
            airspeed_mps = abs(airspeed_mps)

**Comment by sobester** [comment]
Neal, thank you for flagging this up. I must admit I have always been in two minds as to what inputs to allow here due to the ambiguity of whether to accept n airspeeds and one altitude/one airspeed and n altitudes/n of each, how to deal with n of one and m of the other, etc. I'm assuming you were attempting to do n of each as bumpy arrays? In any case, your question reminded me that this needs tightening up in some way.

**Comment by sobester** [comment]
@nagordon This is now fixed in the current version on here (thanks @yaseen157 ), to be included in the next PyPi release. Herewith some examples of various combinations of possible inputs:

```python

isa = atmospheres.Atmosphere()
vs_sl = isa.vsound_mps()

print(isa.mach(vs_sl))
print(isa.mach(vs_sl, 10000))
print(isa.mach(vs_sl, [0, 10000]))
print(isa.mach([vs_sl, vs_sl, vs_sl]))
print(isa.mach([vs_sl, vs_sl, vs_sl], 20000))
print(isa.mach([vs_sl, vs_sl, vs_sl], [0, 10000, 20000]))
```

András
